service: acps-msp-empresa-integracion

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  stage: ${opt:stage, 'dev'}

plugins:
  - serverless-plugin-typescript
  - serverless-offline

functions:
  archivonegativoIntegracion:
    handler: src/fn-archivonegativo-integracion/index.handler
    events:
      - http:
          path: /empresa/archivonegativo-integracion
          method: POST
          cors: true

  bmpIntegracionCreacion:
    handler: src/functions/bpmIntegracionCreacion.handler
    events:
      - http:
          path: /empresa/bpm-integracion
          method: POST
          cors: true

  bpm-sincronizacion:
    handler: src/functions/bpmSincronizacion.handler
    events:
      - http:
          path: /empresa/bpm-sincronizacion
          method: POST
          cors: true

  rcsaIntegracion:
    handler: src/functions/rcsaIntegracion.handler
    events:
      - http:
          path: /empresa/rcsa-integracion
          method: POST
          cors: true

  notificacionLatinia:
    handler: src/functions/documentosClientes.handler 
    events:
      - http:
          path: /empresa/notificacion-latinia
          method: POST
          cors: true        

  notificacionCliente:
      handler: src/functions/notificacionCliente.handler
      events:
        - http:
            path: /empresa/notificacion-cliente
            method: POST
            cors: true

  vdmCondocalm:
      handler: src/functions/vdmCondocalm.handler
      events:
        - http:
            path: /empresa/vdm-Condocalm
            method: POST
            cors: true

custom:
  serverless-offline:
    httpPort: 3001
    host: 0.0.0.0
    printOutput: true
    noTimeout: true
