service: acps-msp-empresa-integracion

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  stage: ${opt:stage, 'dev'}

plugins:
  - serverless-plugin-typescript
  - serverless-offline

functions:
  rcsaIntegracion:
    handler: src/fn-rcsa-integracion/index.handler
    events:
      - http:
          path: /empresa/rcsa-integracion
          method: POST
          cors: true

  bmpIntegracionCreacion:
    handler: src/fn-bpm-integracion-creacion/index.handler
    events:
      - http:
          path: /empresa/bpm-integracion
          method: POST
          cors: true

custom:
  serverless-offline:
    httpPort: 3001
    host: 0.0.0.0
    printOutput: true
    noTimeout: true
